CREATE DATABASE IF NOT EXISTS `crud` DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON crud_ppi.* TO 'user'@'%';
FLUSH PRIVILEGES;
USE `crud`;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `senha` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;